
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Mar 09 17:04:13 CET 2018
//----------------------------------------------------

package yal.analyse;

/** CUP generated class containing symbol constants. */
public class CodesLexicaux {
  /* terminals */
  public static final int FONCTION = 22;
  public static final int FSI = 30;
  public static final int TANTQUE = 24;
  public static final int CONSTANTECHAINE = 32;
  public static final int MULT = 5;
  public static final int EGAL = 16;
  public static final int REPETER = 25;
  public static final int SI = 27;
  public static final int FIN = 20;
  public static final int LIRE = 31;
  public static final int ECR = 21;
  public static final int OU = 14;
  public static final int INF = 10;
  public static final int NON = 15;
  public static final int PAROUV = 7;
  public static final int DIV = 6;
  public static final int EGALEGAL = 11;
  public static final int PLUS = 3;
  public static final int DEBUT = 19;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int RETOURNE = 23;
  public static final int MOINS = 4;
  public static final int ET = 13;
  public static final int IDF = 35;
  public static final int SINON = 29;
  public static final int ALORS = 28;
  public static final int PARFER = 8;
  public static final int CONSTANTEINT = 33;
  public static final int CONSTANTEBOOL = 34;
  public static final int PROGRAMME = 17;
  public static final int POINTVIRGULE = 2;
  public static final int FINTANTQUE = 26;
  public static final int SUP = 9;
  public static final int DIFF = 12;
  public static final int ENTIER = 18;
}

